// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.ECS {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    
    
    public class uFrameECSDocumentationProviderBase : Invert.Core.GraphDesigner.DocumentationDefaultProvider {
        
        public override void GetPages(System.Collections.Generic.List<Invert.Core.GraphDesigner.DocumentationPage> rootPages) {
            base.GetPages(rootPages);
        }
    }
}
