// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.ECS {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    using Invert.Data;
    
    
    public class ExpressionsBase : MultiInputSlot<IExpressionsConnectable> {
        
        public override string Name {
            get {
                return "Expressions";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<Invert.Data.IValueItem> GetAllowed() {
            return Repository.AllOf<IExpressionsConnectable>().OfType<IValueItem>();;
        }
    }
    
    public partial interface IExpressionsConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class TimerBase : SingleInputSlot<ITimerConnectable> {
        
        public override string Name {
            get {
                return "Timer";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return false;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<Invert.Data.IValueItem> GetAllowed() {
            return Repository.AllOf<ITimerConnectable>().OfType<IValueItem>();;
        }
    }
    
    public partial interface ITimerConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
}
